### ISSUE TITLE
Styling issues with sharing menu in Files app 

### ISSUE THREAD

**Issue by MrJohnZoidberg** [mwalbeck/nextcloud-breeze-dark#102]
**Describe the bug**
There are two small styling issues in the sharing menu of the Files app:

![Screenshot_20200315_230621](https://user-images.githubusercontent.com/27244574/76711870-a6e0a080-6713-11ea-88ed-ffb973a1222d.png)

1. The description text in the field for names, Cloud-IDs and mail addresses is not readable, because its color is too dark.

2. There is a white selection field overlapping with other text elements and it seems that its position is not right.

**EDIT:**

![Screenshot_20200315_233807](https://user-images.githubusercontent.com/27244574/76712153-2cfde680-6716-11ea-8744-433062459888.png)

3. The Talk icon is black, I think it has something to do with #93.

**To Reproduce**
1. Go to the Files app
2. Click on Details for a file or folder
3. In the right side menu go to the sharing section

**Expected behavior**
The text should be readable and the white selection field should be dark (maybe?). Also the text should not be overlapping with the selection field.

**Setup (please complete the following information):**
 - Nextcloud version: 18.0.2.2
 - Theme version: 18.0.9
 - Browser and browser version: Firefox 73 & Chromium 80

Thank you for this great app!

**Comment by mwalbeck** [comment]
Hi,

I'll get the talk icon fixed in the next release.

Regarding the 2 other issues, I haven't been able to reproduce them. Can you try the following things and see if it makes a difference:

* Run occ maintenance:repair (Might leave your nextcloud instance without any styling for a few minutes if you use docker)
* Run your browser in safe-mode so all extension are disabled

Browser cache probably isn't an issue, since you have tried with 2 different browsers, but you can also try to clear your browser cache.

**Comment by MrJohnZoidberg** [comment]
Thank you for your help! In the javascript console of my browser I saw that the CSP of my server blocks some resources.

Thanks again :-)

**Comment by mwalbeck** [comment]
Talk icon is fixed in 18.0.10, which has just been released
