### ISSUE TITLE
files created in default files folder

### ISSUE THREAD

**Issue by hackitz** [mwalbeck/nextcloud-breeze-dark#108]
Not sure when this started but i now have 5 files in the default file folder called, stylers.xml, shortcuts.xml, langs.xml, contextmenu.xml and config.xml.
i can remove the files with out any negative effect to nextcloud. but they come back.

**Comment by mwalbeck** [comment]
Hi,

This theme isn't creating any files in any user folders. There isn't even any of those files included in the theme, so I think your issue lies elsewhere.

If you provide a list of apps you have installed on your Nextcloud instance and your config.php file (remember to remove any sensitive information) I can maybe give you an idea of where your problem lies, as I can see you haven't had much luck on the Nextcloud forum.
