### ISSUE TITLE
Mail style improvement

### ISSUE THREAD

**Issue by Leon0402** [mwalbeck/nextcloud-breeze-dark#110]
**Describe the bug**
Personally I think, emails look design wise a little bit off. I attached two different kind of mails to show how it currently is. The first one is an image (which is quite often like that) and the second one plain text.
Especially in the first case it looks really weird, because of the image. But I assume we can't style that, because it's an iframe. So instead I would suggest to leave the frame and black background away. This is also how it is done in the normal theme and most email clients I know.
See the other two attachments. 

It could be probably even more improved (also in the original theme), if there would be some kind of separation between email header and content. But that might be more a task for the email client itself I suppose.

**Screenshots**
![image](https://user-images.githubusercontent.com/33933142/79110195-319bd600-7d7a-11ea-912b-bb26b4f6944f.png)

![image](https://user-images.githubusercontent.com/33933142/79110148-13ce7100-7d7a-11ea-9bd3-e815ecc1d26e.png)

![image](https://user-images.githubusercontent.com/33933142/79110933-d10d9880-7d7b-11ea-9e84-7610817ec56b.png)
![image](https://user-images.githubusercontent.com/33933142/79110973-e1be0e80-7d7b-11ea-9868-c3e843b1b530.png)

**Comment by mwalbeck** [comment]
Thanks for the feedback.

I'm inclined to agree that the current look isn't ideal, but I'm also not happy about the default look. It's been awhile since last I took a closer look at it, but I'm happy to give it a rethink.

Yes, you are correct that HTML based emails can't be styled as they are loaded in an iframe.

I think I'll try and see if I can't find a better way of visually separating the different elements,  and if not, I'll consider changing it to be closer to the default.

**Comment by Leon0402** [comment]
I really think the issue with the default look is that there is no separation between the header and the content. But that seems like something, the app itself should fix and not the custom theme. 
Or is there anything else, you don't like about the default look?

**Comment by mwalbeck** [comment]
I currently don't really use Mail much myself so I had the design of an older version in my head. It used to be, in my opinion, really bad when it came to separating header, content, attachment and replying. It was more or less one big mess. I can see that things have very much changed.

So no, there aren't actually any other problems I have with the default look. I've adjusted the look to be closer to the default
![image](https://user-images.githubusercontent.com/19759293/79129203-13979b00-7da5-11ea-9ec9-5473909adcd9.png)

I generally prefer to not change too much other than colours, unless I really dislike a design decision. When it comes to the current visuals, I'll agree that it would make more sense to find a solution in the app instead of this theme.

**Comment by Leon0402** [comment]
That looks much better already! Such a pitty that we can't change the iframe.

How does it look like if there is a "normal" email, so one without an image (iframe) in it? Like the second Image I posted?

**Comment by mwalbeck** [comment]
Yeah, I agree, it looks better than before. Here's a normal text email

![image](https://user-images.githubusercontent.com/19759293/79134896-c6b8c200-7dae-11ea-83e7-1d33471f67eb.png)

**Comment by Leon0402** [comment]
Nice job! Looking forward to get the update :)

**Comment by mwalbeck** [comment]
Fixed in 18.0.12, which has just been released.

**Comment by justgalak** [comment]
> 
> 
> That looks much better already! Such a pitty that we can't change the iframe.
> 
> How does it look like if there is a "normal" email, so one without an image (iframe) in it? Like the second Image I posted?

We can affect the iframe, but not it's contents.

Mail styles iFrames with:
`.app-mail #app-content .app-content-details #mail-content iframe {}`

It's possible to change at least the background color to sth. grey or blue. Maybe this will make it look less odd.

**Comment by mwalbeck** [comment]
Not really, it will more or less look off no matter what, so I'm just going to stick to the default background colour. I did consider still have the iframe background the main background colour of the theme. That would allow barebones html emails to be styled after the theme, but then we run into issues with font colour.

There could be an argument for a different shade of white/light gray, but it isn't a focus for me at the moment.
