### ISSUE TITLE
Background color for text selection

### ISSUE THREAD

**Issue by Leon0402** [mwalbeck/nextcloud-breeze-dark#111]
**Describe the bug**
The selection color seems to be not right. It's a light grey, which makes the white text behind it hard to read.

![image](https://user-images.githubusercontent.com/33933142/79128736-52792100-7da4-11ea-9a88-681f1a63f82d.png)

Well just while i was writing this, I actually found out that the selection color is different, if you start selecting from above the text (or from the side/bottom). This colour is actually quite nice and the readablity is even better than the Kate Blue (see below) imo (the blue might be a little bit more breezy though ... but that's really not so important)

![image](https://user-images.githubusercontent.com/33933142/79128711-48572280-7da4-11ea-9f27-ec0275c7da00.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/33933142/79128240-7a1bb980-7da3-11ea-8348-230538ab888e.png)

This is how it is in the Text app, although it's still not optimal in my opinion. 

![image](https://user-images.githubusercontent.com/33933142/79128435-cbc44400-7da3-11ea-8cfd-bf9fd3548870.png)

This is Kate and the blue for selection seem better than the one from Text.

**Comment by mwalbeck** [comment]
I've changed the title to make this issue about text selection more in general. The main reason is because the issue with the notes app is an upstream issue and is currently fixed in master.

So for highlighting in general, then yes, it could be better. I propose something similar to Kate:
![image](https://user-images.githubusercontent.com/19759293/79137056-4bf1a600-7db2-11ea-82b3-0537223c9dd7.png)

It more or less sticks to the breeze dark colours and it has a much better contrast with the white text than the current text selection background.

**Comment by mwalbeck** [comment]
Fixed in 18.0.12. Text selection in the Notes app is still not fixed, but will be with their next release.
