### ISSUE TITLE
IE11 Nextcloud header not styled properly

### ISSUE THREAD

**Issue by 11harveyj** [mwalbeck/nextcloud-breeze-dark#123]
**Describe the bug**
Within IE11, the header style is not showing properly unlike in other browsers such as Chromium based browsers (Chome, Edge etc.)

**To Reproduce**
1. Install theme
2. Open nextcloud after clearing cache etc.
3. Login
4. See style issue

**Expected behavior**
Styles should be consistent across all browsers (ideally)

**Screenshots**
IE11:
![image](https://user-images.githubusercontent.com/7346615/80860749-db77cf80-8c61-11ea-90bd-23679dfaedca.png)

Edge (new version based on Chromium):
![image](https://user-images.githubusercontent.com/7346615/80860775-f9ddcb00-8c61-11ea-8210-8e2422d928d9.png)

**Setup (please complete the following information):**
 - Nextcloud version: [e.g. 17.0.3] 18.0.4
 - Theme version [e.g. 17.0.6] 18.0.13
 - Browser and browser version [e.g. Firefox 70, Chrome 72] Internet Explorer 11

**Comment by mwalbeck** [comment]
Hi,

Thanks for reporting this

If it's only the header that's an issue, this could possibly be fixed, but in general I don't have any plans of really supporting IE11. There are really 2 issues, time and access.

Supporting IE11 will take extra time because of the need for more manual testing, and possibly more complicated styling. I would prefer to spend the time I have available to improving the theme instead.

The second issue is that I simply don't have easy access to IE11 to actually develop and test the theme.

Though if it doesn't add to much complexity to the styling, and someone is interested in doing it, I would be happy to help with and merge any pull requests.

**Comment by blackcrack** [comment]
is ie11 no more supported ?
Now it is MS Edge the MS-Browser with Chrome Engine.  
There gives Browser FF, Brave, Whaterfox, Opera, vivaldi, Torch, Epic Privacy Browser, Ghost Browser and many other Browser if we looking to older Browser where be no more Supported, have you a hard work  @mwalbeck 

best regards
Blacky

**Comment by 11harveyj** [comment]
@blackcrack IE11 is more of a legacy browser in my humble opinion to support "enterprise" applications that still require full plugin support (Java, Silverlight, Flash... yes I know you can run flash in Edge/Chrome and other browsers, but you need to go into the site settings to enable it sometimes which is a pain for some, less technically-abled users).
I've reported this issue as something I stumbled across more than anything while I was testing unrelated things. (I personally use the new MS Edge and have IE11 disabled across my network)

You can compare functionality differences here: [Web browser comparison](https://caniuse.com/#compare=ie+11,edge+81,firefox+76,chrome+81,safari+13.1,opera+68,ios_saf+13.4,android+81,op_mob+46,and_chr+81,and_ff+68,and_uc+12.12,and_qq+10.4,baidu+7.12,kaios+2.5)

Fully appreciate @mwalbeck decision on this topic.

**Comment by blackcrack** [comment]
hi @11harveyj  :)

well, it is possible to give directly instructions to the IE from 6 up to 11 in css, my self use Moz.FF and FF disable in the next couples version Adobe Flash.. and i be really not amused about.. not only FF and Chrome support easy more and better the css standard as it has IE does and IE was ever a Stepon in things of correct configuration and support of the web-things, they, so MS has ever his own standard and now finally use they are a webengine who it use the community too and have finally done the step to the community and working together.. well, because this is the only reason why i say.. Edge is well so far, but this is not for me a reason to use Edge as standard browser.. i stay so long at FF up to is it unusable.. the Brave browser is allready installed ;)
best regards
Blacky
