### ISSUE TITLE
[Feature Request] Add to Accessibility App core

### ISSUE THREAD

**Issue by sunjam** [mwalbeck/nextcloud-breeze-dark#171]
Breeze Dark is a solid theme that has been working well in my testing.  I'd like to request it become formally bundled permanently into the Accessibility app itself, since the only issue I encounter is Breeze needing to be updated for each version release.  No worries if this isn't possible.  Thanks for considering, and great work on this app.

The default Dark theme has issues in certain apps such as Circles and ocDownloader, so I don't think of that as a specific set back.

**Comment by mwalbeck** [comment]
Hi, this response comes a bit late, but better late than never I guess. Before I close this issue I want to atleast give my point of view, but a quick TLDR is that I think this theme is better as an app.

Nextcloud has defined some design guidelines so all apps have a similar look and the overall building blocks are kind of the same. The official dark theme is setup with that in mind, so if you follow the guidelines, the dark theme should work with your app. So Nextcloud expects you to build your app so it works with their theme, which makes sense as they are the platform.

I work the other way around. I built the the theme around other peoples apps. Though as the official dark theme improves and more and more apps follow the guidelines more closely, my job of theming gets easier, as I use the same method used for the official dark theme, but there is still a good chunk of manual theming needed on top to create the theme I want to make.

Since I built the theme around other peoples apps it's, more often than not, on me to fix any theming issue that come up with newer releases of said apps. If Breeze Dark is apart of the Accessibility app any updates to the theme could only be released with a new point release of Nextcloud. Whereas now I can release an update whenever it's needed. Breeze Dark is also slowly evolving with extra features, which are unique to this theme and most likely won't come to the official one. So, in a way, there are less restrictions by keeping it as a separate app and the way this theme is currently developed, I think it benefits from that.

I hope that made sense and thank you for using the theme.
