### ISSUE TITLE
Login image not shown

### ISSUE THREAD

**Issue by Max0440** [mwalbeck/nextcloud-breeze-dark#174]
If I upload a login image in the theming settings and select the Breeze Dark theme as default, the image is not shown on the login page. If I don't select Breeze Dark as default, the image is displayed.

Breeze Dark selected as default and uploaded image:
![image](https://user-images.githubusercontent.com/43546333/96354997-541dfb80-10dd-11eb-97a1-34646c994a76.png)

Breeze Dark not selected as default and uploaded image:
![image](https://user-images.githubusercontent.com/43546333/96355008-7b74c880-10dd-11eb-85c2-ac5dd5160fe2.png)

 - Nextcloud version: 20.0.0
 - Theme version 20.0.0
 - Browser and browser version: Chrome 86

I hope you can fix this problem and I didn't do anything wrong reporting this bug!

**Comment by mwalbeck** [comment]
It's an issue I'm aware of but I don't have a proper fix at the moment. The issue is present when index.php is visible in the url for your nextcloud instance. I can currently give two workarounds:

1. I'm assuming you're using apache here, so please correct me if I'm wrong. You can follow the steps from the documentation and switch to using "pretty urls", aka urls without index.php in them, https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html#pretty-urls

2. You can install the custom css app from the nextcloud app store and add the following css rule.
```
body#body-login {
	background-image: url('../../../index.php/apps/theming/image/background'), url('../../../core/img/background.png');
}
```

I hope that helps, and nothing wrong with reporting this issue. You filled out the bug report with screenshots and all, so no complaints here.

**Comment by Max0440** [comment]
Thanks, I tried the first solution and it worked
