### ISSUE TITLE
Change Highlight Color

### ISSUE THREAD

**Issue by unamundan** [mwalbeck/nextcloud-breeze-dark#184]
Thanks for such an AWESOME app. It’s a perfect alternative for Nextcloud’s built-in dark theme.

I’d love to change the hover / highlight / select color from the standard BLUE to something else.

**Comment by mwalbeck** [comment]
I'm currently trying to find the best solution for allowing generic customisation without having to fork the theme. What you want to do is more or less already possible. For all the colours in the theme I use CSS variables, which means the colours can easily be changed by me or overridden after the fact.

My previous recommendation regarding customisations was the Custom CSS app for Nextcloud, because that makes it easy to add custom CSS to Nextcloud and do stuff like overriding CSS variables. The main problem, though, is the fact that the CSS from the Custom CSS app is applied globally. So I can really only be used on Nextcloud instances where Breeze dark is only theme being used. If you don't mind that I can assist with which variables to override, if needed.

When I figure out which solution I want to go with, then I'll most likely make a new issue and closed all the related ones.

**Comment by unamundan** [comment]
Thanks, @mwalbeck. I’ll wait until you decide how to tackle customization option. It’s fine as-is! And I’d rather not go tinkering unnecessarily. I look forward to whatever solution you implement.

**Comment by mwalbeck** [comment]
To resolve this I plan on implementing an option for providing custom css like the existing app, but integrated so it only applies when the theme is active. That seems like the best solution and will allow users to do pretty much whatever they want when it comes to customisations.

I'm going to close this issue in favor of #204

**Comment by mwalbeck** [comment]
This feature is now available in the latest release and I just wanted to let you or anyone else the easiest way to change the colours. There are a handful of CSS variables used for theme and the ones related to hover and highlight are:
```
    --color-background-hover: var(--color-hover-blue) !important;

    --color-primary: var(--color-plasma-blue) !important;
    --color-primary-light: var(--color-primary) !important;
    --color-primary-element: var(--color-primary) !important;
    --color-primary-element-light: var(--color-primary) !important;
```
So let's say you wanted to change the hover colour to green you can specify this CSS rule:
```
:root {
  --color-background-hover: green !important;
}
```
You can just change the colour to whatever you want using hex or rgba values. The same applies to all the other variables as well, just add them inside the ```:root``` selector.

**Comment by KaiBuskirk** [comment]
perfect little detail.....
kai

**Comment by unamundan** [comment]
Thanks, @mwalbeck!
