### ISSUE TITLE
Collabora theme issue

### ISSUE THREAD

**Issue by axheli** [mwalbeck/nextcloud-breeze-dark#187]
Is there a way to remove the dark theme from the image below i think it looks a little off with collabora 
![image](https://user-images.githubusercontent.com/59488153/100258069-3b8ad780-2f0c-11eb-8857-0ac5263ae667.png)

**Comment by mwalbeck** [comment]
The collabora integration was changed so now they detect and somewhat use the colours Nextcloud uses which is why it looks like it does. I plan on disabling the theming for collabora in the next update, but it isn't straight forward so I haven't had time to do it yet. You can keep an eye on #183 for future updates.

**Comment by axheli** [comment]
@mwalbeck thanks for the quick reply. okay i will keep an eye on this and close this one. Thank you so much buddy.
