### ISSUE TITLE
Mail text isn't show clear in some of the mails

### ISSUE THREAD

**Issue by XDavidT** [mwalbeck/nextcloud-breeze-dark#190]
**Which app would you like to have styled**:
Mail app need to improve

**Your setup (please complete the following information):**
-   Nextcloud version: 20.0.2
-   Browser: Firefox

Most of email is look fine, some of them get text darker and some brighter..
But now found emails I can't read: https://imgur.com/a/B3GME1Y

**Comment by mwalbeck** [comment]
Without a concrete email I can work with I don't think there is much I can do. There are to types of emails, plain text and HTML. The plain text emails I apply normal styling to should all look fine, but for the most part emails being sent are normally HTML emails.

For HTML emails I have more or less no control over how they are presented and currently I just show them as is. All HTML emails are also shown with a white background behind, so the formatting of that email is definitely off. Maybe they are overusing images and the email will look fine if you allow those.

But all in all, maybe there is something I can do if I have access to the specific emails but most likely not.

**Comment by XDavidT** [comment]
> Without a concrete email I can work with I don't think there is much I can do. There are to types of emails, plain text and HTML. The plain text emails I apply normal styling to should all look fine, but for the most part emails being sent are normally HTML emails.
> 
> For HTML emails I have more or less no control over how they are presented and currently I just show them as is. All HTML emails are also shown with a white background behind, so the formatting of that email is definitely off. Maybe they are overusing images and the email will look fine if you allow those.
> 
> But all in all, maybe there is something I can do if I have access to the specific emails but most likely not.

The email was forward to the email in your profile.
But still, I thing maybe to ignore any background, and force the dark background can fix this ? and then to force the font color against..

**Comment by mwalbeck** [comment]
Thanks for the email. I figured out the issue. With one of the updates to Mail, they changed the CSS classes and id's a bit so some of the themes styling was no longer being applied. I have now fixed that.

The issue is HTML email are shown in an embedded iframe, and a stylesheet from the parent webpage can't style content in an iframe. So previously I have just set the background of the iframe to a light colour so HTML emails with no background-color set would show properly. This styling was no longer being applied and made the email you sent unreadable as it had no background set. I didn't notice this before now because all the HTML emails I have in my test email account have a background-color specified.

Thanks for reporting the issue.
