### ISSUE TITLE
Styling tweak for "deck" app.

### ISSUE THREAD

**Issue by Ryonez** [mwalbeck/nextcloud-breeze-dark#27]
Sorry to bother you again.
Would you mind checking out the styling for the Deck up please? I've notice the timing note things are a little hard to read.
Hours ago looks good:
![image](https://user-images.githubusercontent.com/16157130/42721383-386025ce-878e-11e8-97c7-9b70a9c67de1.png)
Minutes ago is pretty harsh:
![image](https://user-images.githubusercontent.com/16157130/42721376-1d3e0cfc-878e-11e8-80b8-05f05b8e8e63.png)
Continuing to add time, this is the next color:
![image](https://user-images.githubusercontent.com/16157130/42721394-5e005c22-878e-11e8-9b0d-b73e5b941471.png)
Next colour to show is:
![image](https://user-images.githubusercontent.com/16157130/42721406-76a7a99c-878e-11e8-881e-aa13caed7000.png)

That's all I've found for now.
I've been exploring and settling into using nextcloud, so I'll be poking about in some of the dusty corners >.<

**Comment by mwalbeck** [comment]
I appreciate the help. I don't have enough time to check all the dusty corners myself, and since there is no real way to automate it, I'm happy to have some assistance.

I hope you are enjoying Nextcloud and my theme. Whatever you may find in those pesky corners you're more than welcome to create more issues, it will definitely be appreciated.

**Comment by Ryonez** [comment]
I have been enjoying them both. And I'll let you know of anything else I notice.
Sorry for the spelling/grammer mistakes, I've been up for a while now, so I better go before it get worse.
