### ISSUE TITLE
Don't replace login-screen background

### ISSUE THREAD

**Issue by WereCatf** [mwalbeck/nextcloud-breeze-dark#283]
If the admin has set up a login-screen background-image, this theme shouldn't be replacing it. It's one thing to theme the login-screen elements, but overriding the background-image is another thing, rendering the option to set one up in the first place useless! Yes, one can fix that with custom CSS, but it's just silly to have to.

If nothing else, simply add a checkbox for "Override login-screen background-image."

**Comment by mwalbeck** [comment]
Hi,

This issue is documented in the README together with two workarounds: https://github.com/mwalbeck/nextcloud-breeze-dark#login-image-not-shown-when-theme-is-enabled

It's an issue that's present if you aren't using pretty URLs. Everything works as intended if you're using pretty URLs.

Yes, one of the workarounds is adding a custom CSS rule, but since the app provides a way to add custom CSS without having to install another app, I don't see it as a big issue. Considering what is needed to add a checkbox specifically for the background image I don't currently see it as a feasible option.

If the two workarounds aren't what you're looking for, then there is also an option to disable theming of the login page entirely. That can be found under the theming settings in Nextcloud.

**Comment by mwalbeck** [comment]
It seems that Nextcloud now handles the redirect properly if you request the custom background image with index.php in the URL while using pretty urls. So I'll be adding index.php to the default URL used for getting custom login screen background in the next release, which means It'll work out of the box with or without pretty urls.

095f650bff676c7a25c42efe6da98f28da987826
