### ISSUE TITLE
Styling for Nextcloud 14.0

### ISSUE THREAD

**Issue by adx442** [mwalbeck/nextcloud-breeze-dark#32]
![2018-09-13_085239](https://user-images.githubusercontent.com/31186396/45492724-a76d3500-b732-11e8-81f0-e06417f3bf14.png)

With a standard Nextcloud 14.0 installation, the Apps area, Settings areas, and Control Panel drop down menu are wrongly themed, with light text on a white background.  I have tried this with the Theming app installed and uninstalled, using incognito mode to verify uncached data.

**Comment by mwalbeck** [comment]
Hi,

I'm aware of the problem and I'm very close to being done with the styling for Nextcloud 14. I haven't had a lot of time to work on it but it should be out soon.

I can also add a bit more info here about the details of NC 14, because they have changed a lot under the hood, when it comes to styling. What this means is they are going to be a few changes in the look of the theme. This changes will make it so less work needs to be done between Nextcloud releases and hopefully less work when it comes to styling apps.

**Comment by adx442** [comment]
Awesome.  Thanks so much for the continuing work on this theme!

**Comment by mwalbeck** [comment]
There are some more things I need to look at and consider before I'm going to officially publish the Nextcloud 14.0 release. So for now, I have published the changes I've made so far, to the develop branch. There shouldn't be any mayor problems, only some small inconsistencies here and there.

**Comment by mwalbeck** [comment]
Hi,

Thanks for taking interest in the theme. I have been traveling lately for various reasons, but have managed to quite a nice amount of work done on the theme. I'm aiming to have a release out with the essential things done in the beginning of the upcoming week.

This upcoming release will have a select group of apps styled and the following release will have styling checked and updated for the rest. Much of the work I'm doing now is mainly removing redundant code and making small tweaks. So hopefully it should be much easier to update the theme to future Nextcloud releases.

**Comment by mwalbeck** [comment]
Okay, I got more or less done with what I set out to do for the first NC14 release so I have decided to publish it and merge the changes to master.
