### ISSUE TITLE
Permanent Internal Server Error after attempting to apply theme

### ISSUE THREAD

**Issue by juicetin** [mwalbeck/nextcloud-breeze-dark#61]
Hi,

I'm not sure to what extent this theme was involved in this, but I'm not sure where else to report/start given what I know so far.

My nextcloud setup was using docker-compose. From a working instance, as per the README, I unzipped the release contents inside `theme/nextcloud-breeze-dark`, and added a single line in the `config/config.php` file - `'theme' => 'nextcloud-breeze-dark',`. I refreshed the nextcloud page, and got internal server errors - nothing in the web UI would load beyond this. 

I undid these changes - both the `config.php` change, and even removed the theme folder - same result. `docker-compose down` and `up` again didn't resolve this either.

There seemed to be nothing at all in the server logs - either `/var/log/apache2/error.log` or `/var/log/apache2/access.log`.

What in the theme could have broken the server so badly, and how can the damage be undone?

Thanks.

**Comment by mwalbeck** [comment]
Hi, 

As far as I know it isn't possible for the theme to really do this. The theme doesn't touch any important parts of nextcloud but is merely place on top as an extra layer of visual styling.

The thing that might be the culprit is a missing comma or quote in the config.php. I can't quite remember nextcloud's response to syntax errors in the config.php. If possible you're welcome to share it, if you do please remember to remove any sensitive information.

If that isn't the case is the page showing the internal server error giving any other information that could be useful?

You could also check the nextcloud log file, it should be located at the root of your nextcloud data directory.

**Comment by juicetin** [comment]
I tried again on a fresh install with exactly the same result unfortunately - and in a separate instance, I tried simply adding the line `'theme' => 'example',` (`example` exists in the `themes/` folder as per the auto generated `config.sample.php` as well - same result).

As I described here - https://help.nextcloud.com/t/added-theme-line-to-config-php-internal-server-error-on-all-sreens/53716, Nextcloud didn't generate logs of any sort.

I'll close this bug as it seems like a bug in Nextcloud itself, and not to do with your theme. Thanks!
