### ISSUE TITLE
missing icons activity, deck, and delete

### ISSUE THREAD

**Issue by xxKeith20xx** [mwalbeck/nextcloud-breeze-dark#69]
On Nextcloud 16.0.4 and just cloned `b9a9fd6` . Everything looks fine but the activity, deck, delete, and svgs are missing now and I don't see them in `./core/img/` either.

Thanks for the theme!

**Comment by mwalbeck** [comment]
Thanks for using the theme.

Just as a heads up, the current HEAD of master is intended to be used with NC17, as there "breaking" changes between releases and to keep the theme small and easier to maintain, I don't make them backwards compatible. Though, if I remember correctly there were only small breaking changes this time around, so you shouldn't have too many problems. I also tend to only focus on the latest NC release because of time constraints. I am open to backporting or updating the theme for older versions when requested, as long as the NC release is still officially supported.

With that out of the way. I experienced that myself and is just a caching issue related to the big icon transition for this new release. Here is what you can do to fix it:

first run the occ command **maintenance:theme:update** as see if that fixes it. 

If not run the following occ command. Beware that this command removes all cached styling and it takes awhile for Nextcloud to regenerate it, so your instance might be unusable for a couple of minutes: **maintenance:repair**

If you have run both, and it hasn't been fixed, try clicking on the icons, for example, the activity app in the nav bar, for some reason that did it for me, after I ran **maintenance:repair**

**Comment by xxKeith20xx** [comment]
Understandable! I generally upgrade to the latest after a few point releases so 17 is coming soon. That said, `maintenance:theme:update` fixed it. Thanks!

**Comment by mwalbeck** [comment]
Great, good to hear.
