### ISSUE TITLE
Make it available in Nextcloud app store

### ISSUE THREAD

**Issue by tiotrom** [mwalbeck/nextcloud-breeze-dark#77]
Isn't it possible to make this theme available in the nextcloud store so people can easily install it and get updates? I am wondering if this would be possible. Cheers!

**Comment by mwalbeck** [comment]
I had a quick look and the current way I'm doing things has actually been deprecated, but not marked for removal, yet. From what I can see the nextcloud devs are pushing for the theming app, and in cases where more advanced control is need, an app.

So with that in mind, I guess I better get to work.

**Comment by mwalbeck** [comment]
I have create a branch called app with an initial version. Currently it works as is, for Nextcloud core. I have a lot of things I would like to change with the app release, to better integrate it with Nextcloud. With that said I'm hoping to have it ready for Nextcloud 18, which is probably going to be an app only release. The reason for this is simple, the styling for the 2 are slightly different because of how Nextcloud handles them, and I simply don't have time to maintain 2 different versions of the theme.

**Comment by mwalbeck** [comment]
And here we are folks. https://apps.nextcloud.com/apps/breezedark

Just a heads up, when you first switch, some icons might not have the correct color (mainly files navigation sidebar). It should sort itself out after a while, but if it doesn't let me know.

**Comment by sdellenb** [comment]
Awesome, thanks!

No issues so far, except icon color when switching back to the default theme (for testing) - browser caching issue.

**Comment by tiotrom** [comment]
Brilliant! Thank you!
