### ISSUE TITLE
Styling for NC 12

### ISSUE THREAD

**Issue by irule311** [mwalbeck/nextcloud-breeze-dark#9]
Styling doesn't work for NC 12 yet. There was a major overhaul of the interface, so it may be difficult to implement quickly. It's slated for release in a few weeks.

**Comment by mwalbeck** [comment]
I've slowly been working on it, and yes, there are quiet a few changes so I've taken this chance to clean up the code aswell. No idea if it will be ready for release, but I'll be sure to keep you updated as we get closer to the release of Nextcloud 12.

**Comment by mwalbeck** [comment]
Okay so Nextcloud 12 has been released. It caught me a bit by surprise since there was no RC this time around.

The theme is almost done, still have to check the theming on a few more apps and few other issue here and there, aswell as some new apps that needs theming. After that is done I'm going to continue with the 3rd party apps.

There is a 12 branch where you can download the theme for NC 12 if you want to test it. I've updated the Styling for Apps issue to reflect progress for NC 12 theming so you can check there for progress. Any apps that were previously themed should more or less work, but if they haven't been check off on the list then haven't the tested yet.

I'll moved NC 12 to master once the official stuff is themed.

**Comment by irule311** [comment]
Wow awesome! That is some really fast work! I'll probably update to Nextcloud 12 today and see how it looks.

**Comment by irule311** [comment]
The base NC theme is perfect from what I see so far! I understand that some apps are not completed yet, however the LDAP app isn't part of the list. Its not a huge deal for me, since I personally will not be using it.
![image](https://cloud.githubusercontent.com/assets/10052885/26333332/64050772-3f22-11e7-87e4-9827921e4a64.png)

**Comment by mwalbeck** [comment]
NC 12 code has been moved to master
