### ISSUE TITLE
Icons stay light after deactivating

### ISSUE THREAD

**Issue by hypervtechnics** [mwalbeck/nextcloud-breeze-dark#93]
**Describe the bug**
After deactivating the app some icons like the favorite/shared icon in the files app stay light.

**To Reproduce**
1. Install the app
2. Go to files app
3. Deactivate the app
4. Go to files app

**Expected behavior**
Restore old icons (the darker ones for the light/default theme)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10027956/74267422-4f12dc00-4d06-11ea-8942-cc64d0936360.png)
![grafik](https://user-images.githubusercontent.com/10027956/74267494-7073c800-4d06-11ea-9315-4990897c5b92.png)

**Setup (please complete the following information):**
 - Nextcloud version: 18.0.0
 - Theme version: 18.0.4
 - Browser and browser version: Firefox 72.0.2

**Additional context**
Also tried to reload using Ctrl + Shift + R. Problem only in files app. In settings the icons have the correct color.

**Comment by mwalbeck** [comment]
Hi,

It happens because Nextcloud is caching everything, and isn't always super quick to register changes. So after awhile it should fix itself. For a quick fix you can run **occ maintenance:repair** and let Nextcloud rebuild it's sass and image cache, after which everything should be in order.

But just a heads up if you do run the above commands and you're using docker, it might take a few minutes for the cache to rebuild, so your Nextcloud instance won't have any styling during that time. So far I've only experienced this with docker installs.

**Comment by hypervtechnics** [comment]
Worked! Thank you very much! 😄

**Comment by TessyPowder** [comment]
Could this please be done automatically ?
I had the same problem and had to search quite a while before i found this

**Comment by mwalbeck** [comment]
@TessyPowder I've had a few other reports on this, so it's definitely on my radar. The scaffolding is there in the app structure, I just need to figure out if the right functionality is exposed in the API. I'll pin this issue until I've had the time to properly look into it, hopefully that will help a bit with visibility of this issue.

**Comment by TessyPowder** [comment]
It could be a good idea to look into the steps maintenance:repair does, find out wich step clears the cache and if this step can be triggered without the other repair steps. As far as i know apps can access occ via an api so it should be possible to implement a soulution.

**Comment by mwalbeck** [comment]
Thanks for the tip. I had a look and sadly the function that clears the sass cache isn't available through the public API. I would also be slightly hesitant to use it because the sass recompilation when using docker can sometimes take a while, which would leave the instance without any styling for a few minutes. I see this as acceptable when manually running the occ command but not when just disabling the theme.

I have 2 other ideas of how to accomplish this. The first is a very much maybe, but would be easier to implement than the second. The second is fairly certain to work, at least for the majority of icons. I'd should only be edge cases where there might be an issue, but maybe a different way of styling those specific edge cases would be a solution.

I'll hopefully have some time in the weekend to figure out what works best, and then I'll provide an update.

**Comment by mwalbeck** [comment]
I've had a look at the 2 options and the first one didn't work, so that leaves the second option. Currently I'm replacing the CSS variables for all the icons, so that Nextcloud would just pick my icon version over the standard ones. That has work fairly well in most cases, but there have been a few situations where it hasn't worked. The work around for those cases has been to create a new variable with the proper naming scheme and then telling Nextcloud to use that variable instead of the standard one. This has had the added benefit that when you disable the theme, the icon cache is still not be refreshed, but Nextcloud reverts to the old icons, because the CSS styling telling Nextcloud to use a different icon is gone.

**Comment by mwalbeck** [comment]
This should now be fixed. The new release (18.0.7) will be out as soon as I can push the changelog and version bump to github (They are having some issues). There might be some icons I've missed, which will turn up black when using the theme, as I have to specify styling for each icon, instead of overwriting the default variables.

If you're still experiencing this issue after updating to the newest version, this is most likely because the old variables are still stored in the icon cache. Running **occ maintenance:repair** will fix that. Afterwards you should be able to disable/enable the theme to your heart's content, with no icon issues (barring any browser caching).

**Comment by mwalbeck** [comment]
New release has just been published

**Comment by hypervtechnics** [comment]
Thank you very much for providing the fix! Also thank you that you even care when people try to deactivate your app! 😊
