### ISSUE TITLE
cannot be reverted - kills the default CSS

### ISSUE THREAD

**Issue by jcheger** [mwalbeck/nextcloud-breeze-dark#99]
**Describe the bug**
After uninstallation, the default theme does not show icons anymore.

**To Reproduce**
1. install Breeze Dark
2. disable or uninstall Breeze Dark
3. icons are here, but not visible anymore

**Expected behavior**
Should be fully revertible. Definitely not a cache issue.

**Screenshots**
![Files - Nextcloud - Google Chrome_033](https://user-images.githubusercontent.com/4332314/75234927-bd05db80-57bb-11ea-95c7-48a1b14e9e60.png)

**Setup (please complete the following information):**
 - Nextcloud version: [e.g. 18.0.1]
 - Theme version [e.g. 18.0.6]
 - Browser and browser version [e.g. Firefox 73.0, Chrome 68.0.3440.106]

**Comment by mwalbeck** [comment]
Hi,

I'm aware of the issue and I'm currently working on a fix #93 

It's a Nextcloud caching issue, and can be fixed with **occ maintenance:repair**. That will clear the icon cache and show the proper icons. Though just a heads up, if you use docker for Nextcloud, running the above command, you might experience a loss of all styling for a few minutes.

**Comment by jcheger** [comment]
Thanks for the trick. With breezedark disabled, it was a huge mess. But after plugin removal, it works as expected.

If someone needs to uninstall breezedark in CLI:
* **occ app:remove breezedark**
* **occ maintenance:repair**
